"""Add CMS tables (pages, page_sections, content_blocks)

Revision ID: 4fb063878ac8
Revises: 
Create Date: 2026-02-04 12:53:41.152096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb063878ac8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('page_type', sa.String(length=50), nullable=True),
    sa.Column('legacy_yaml_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_url', sa.String(length=500), nullable=False),
    sa.Column('to_url', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_from_url'), 'redirects', ['from_url'], unique=False)
    op.create_index(op.f('ix_redirects_id'), 'redirects', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_draft_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_subtype', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('document_data', sa.JSON(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_draft_id'], ['guest_drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('page_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('background_style', sa.String(length=100), nullable=True),
    sa.Column('css_classes', sa.Text(), nullable=True),
    sa.Column('container_width', sa.String(length=50), nullable=True),
    sa.Column('padding_y', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_sections_id'), 'page_sections', ['id'], unique=False)
    op.create_index(op.f('ix_page_sections_page_id'), 'page_sections', ['page_id'], unique=False)
    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('css_classes', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['page_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_blocks_id'), 'content_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_content_blocks_section_id'), 'content_blocks', ['section_id'], unique=False)
    op.drop_constraint(op.f('global_inn_limits_inn_key'), 'global_inn_limits', type_='unique')
    op.drop_index(op.f('idx_global_inn_limits_inn'), table_name='global_inn_limits')
    op.create_index(op.f('ix_global_inn_limits_id'), 'global_inn_limits', ['id'], unique=False)
    op.create_index(op.f('ix_global_inn_limits_inn'), 'global_inn_limits', ['inn'], unique=True)
    op.drop_constraint(op.f('guest_drafts_draft_token_key'), 'guest_drafts', type_='unique')
    op.drop_index(op.f('idx_guest_drafts_document_type'), table_name='guest_drafts')
    op.drop_index(op.f('idx_guest_drafts_draft_token'), table_name='guest_drafts')
    op.drop_index(op.f('idx_guest_drafts_expires_at'), table_name='guest_drafts')
    op.drop_index(op.f('idx_guest_drafts_user_id'), table_name='guest_drafts')
    op.create_index(op.f('ix_guest_drafts_draft_token'), 'guest_drafts', ['draft_token'], unique=True)
    op.create_index(op.f('ix_guest_drafts_id'), 'guest_drafts', ['id'], unique=False)
    op.drop_constraint(op.f('guest_drafts_user_id_fkey'), 'guest_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'guest_drafts', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'guest_drafts',
        existing_comment='Черновики документов гостей. Сохраняются до регистрации, хранятся 7 дней.',
        schema=None
    )
    op.drop_index(op.f('idx_inn_usage_inn'), table_name='inn_usage')
    op.drop_index(op.f('idx_inn_usage_user_id'), table_name='inn_usage')
    op.create_index(op.f('ix_inn_usage_id'), 'inn_usage', ['id'], unique=False)
    op.create_index(op.f('ix_inn_usage_inn'), 'inn_usage', ['inn'], unique=False)
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.drop_index(op.f('idx_payments_user_id'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_column('payments', 'is_test')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               comment=None,
               existing_comment='Телефон пользователя (из Яндекс OAuth или вручную)',
               existing_nullable=True)
    op.drop_constraint(op.f('users_yandex_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=False)
    op.create_unique_constraint(op.f('users_yandex_id_key'), 'users', ['yandex_id'])
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               comment='Телефон пользователя (из Яндекс OAuth или вручную)',
               existing_nullable=True)
    op.add_column('payments', sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Тестовый платеж (не реальные деньги)'))
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('idx_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.drop_index(op.f('ix_inn_usage_inn'), table_name='inn_usage')
    op.drop_index(op.f('ix_inn_usage_id'), table_name='inn_usage')
    op.create_index(op.f('idx_inn_usage_user_id'), 'inn_usage', ['user_id'], unique=False)
    op.create_index(op.f('idx_inn_usage_inn'), 'inn_usage', ['inn'], unique=False)
    op.create_table_comment(
        'guest_drafts',
        'Черновики документов гостей. Сохраняются до регистрации, хранятся 7 дней.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'guest_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('guest_drafts_user_id_fkey'), 'guest_drafts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_guest_drafts_id'), table_name='guest_drafts')
    op.drop_index(op.f('ix_guest_drafts_draft_token'), table_name='guest_drafts')
    op.create_index(op.f('idx_guest_drafts_user_id'), 'guest_drafts', ['user_id'], unique=False)
    op.create_index(op.f('idx_guest_drafts_expires_at'), 'guest_drafts', ['expires_at'], unique=False)
    op.create_index(op.f('idx_guest_drafts_draft_token'), 'guest_drafts', ['draft_token'], unique=False)
    op.create_index(op.f('idx_guest_drafts_document_type'), 'guest_drafts', ['document_type'], unique=False)
    op.create_unique_constraint(op.f('guest_drafts_draft_token_key'), 'guest_drafts', ['draft_token'])
    op.drop_index(op.f('ix_global_inn_limits_inn'), table_name='global_inn_limits')
    op.drop_index(op.f('ix_global_inn_limits_id'), table_name='global_inn_limits')
    op.create_index(op.f('idx_global_inn_limits_inn'), 'global_inn_limits', ['inn'], unique=False)
    op.create_unique_constraint(op.f('global_inn_limits_inn_key'), 'global_inn_limits', ['inn'])
    op.drop_index(op.f('ix_content_blocks_section_id'), table_name='content_blocks')
    op.drop_index(op.f('ix_content_blocks_id'), table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_page_sections_page_id'), table_name='page_sections')
    op.drop_index(op.f('ix_page_sections_id'), table_name='page_sections')
    op.drop_table('page_sections')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_redirects_id'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_from_url'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
